In [1]:

import numpy

In [3]:
numpy.loadtxt(fname = './inflammation-01.csv',delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [5]:
data1= numpy.loadtxt(fname = './inflammation-01.csv',delimiter=',')

In [6]:
print(data1)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [7]:
data.shape

(60, 40)

In [8]:
print(data1[1,1])

1.0


In [9]:
print(data1[0,0])

0.0


In [10]:
subdata = data1[0:3,36:]

In [11]:
print(subdata)

[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]


In [12]:
print(subdata.shape)

(3, 4)


In [13]:
subdata = data1[0:3,36:39]

In [14]:
print(subdata)

[[ 2.  3.  0.]
 [ 1.  1.  0.]
 [ 2.  2.  1.]]


In [ ]:
print(subdata)